name: calzada
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dio_logger: ^4.0.8+8
  dio_smart_retry: ^1.2.0
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.6.1
  get: 4.6.3
  multiple_result: ^1.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/washingmachine.png
