name: calzada
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.1
  get: 4.6.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/washingmachine.png
